@echo off
REM Femas HR Installation Script for Windows
REM This script will:
REM 1. Prompt for Femas credentials
REM 2. Prompt for check-in and checkout times
REM 3. Create .env file
REM 4. Register tasks in Windows Task Scheduler

echo ========================================
echo   Femas HR Auto Check-in/out Installer
echo ========================================
echo.

REM ---- Check if running as Administrator ----
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [ERROR] Please run this batch file as Administrator
    echo.
    echo Right-click this file and select "Run as Administrator"
    echo.
    pause
    exit /b 1
)

SET SCRIPT_DIR=%~dp0
SET ENV_FILE=%SCRIPT_DIR%.env

echo [Step 1/5] Configure Femas Credentials
echo ========================================
echo.

REM ---- Prompt for username ----
set /p FEMAS_USER="Enter Femas username: "
if "%FEMAS_USER%"=="" (
    echo [ERROR] Username cannot be empty
    pause
    exit /b 1
)

REM ---- Prompt for password ----
set /p FEMAS_PASS="Enter Femas password: "
if "%FEMAS_PASS%"=="" (
    echo [ERROR] Password cannot be empty
    pause
    exit /b 1
)

echo.
echo [Step 2/5] Configure Check-in/out Times
echo ========================================
echo.

REM ---- Prompt for check-in time ----
set /p CHECKIN_TIME="Enter check-in time (Format: HH:MM, e.g., 08:50): "
if "%CHECKIN_TIME%"=="" set CHECKIN_TIME=08:50
echo Check-in time set to: %CHECKIN_TIME%
echo.

REM ---- Prompt for checkout time ----
set /p CHECKOUT_TIME="Enter check-out time (Format: HH:MM, e.g., 19:00): "
if "%CHECKOUT_TIME%"=="" set CHECKOUT_TIME=19:00
echo Check-out time set to: %CHECKOUT_TIME%
echo.

REM ---- Create .env file ----
echo [Step 3/5] Creating configuration file (.env)
echo ========================================
echo.

(
echo # Femas Cloud Credentials Configuration
echo # This file is auto-generated by install.bat
echo # IMPORTANT: Never commit .env to git!
echo.
echo FEMAS_USER="%FEMAS_USER%"
echo FEMAS_PASS="%FEMAS_PASS%"
) > "%ENV_FILE%"

if exist "%ENV_FILE%" (
    echo [SUCCESS] .env file created at: %ENV_FILE%
) else (
    echo [ERROR] Failed to create .env file
    pause
    exit /b 1
)

echo.
echo [Step 4/5] Registering check-in task to Task Scheduler
echo ========================================
echo.

REM ---- Register check-in task ----
schtasks /Create /TN "FemasHR Check-in" /TR "\"%SCRIPT_DIR%checkin.bat\"" /SC DAILY /ST %CHECKIN_TIME% /F >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo [SUCCESS] Check-in task registered
    echo   - Task Name: FemasHR Check-in
    echo   - Run Time: %CHECKIN_TIME% (Daily)
    echo   - Execute: %SCRIPT_DIR%checkin.bat
) else (
    echo [ERROR] Check-in task registration failed
)

echo.
echo [Step 5/5] Registering check-out task to Task Scheduler
echo ========================================
echo.

REM ---- Register checkout task ----
schtasks /Create /TN "FemasHR Check-out" /TR "\"%SCRIPT_DIR%checkout.bat\"" /SC DAILY /ST %CHECKOUT_TIME% /F >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo [SUCCESS] Check-out task registered
    echo   - Task Name: FemasHR Check-out
    echo   - Run Time: %CHECKOUT_TIME% (Daily)
    echo   - Execute: %SCRIPT_DIR%checkout.bat
) else (
    echo [ERROR] Check-out task registration failed
)

echo.
echo ========================================
echo     Installation Complete!
echo ========================================
echo.
echo [Configuration Summary]
echo.
echo Username: %FEMAS_USER%
echo Check-in time: %CHECKIN_TIME% (Daily)
echo Check-out time: %CHECKOUT_TIME% (Daily)
echo.
echo [Important Notes]
echo.
echo 1. Weekends and Taiwan national holidays will be skipped automatically
echo.
echo 2. View tasks in Task Scheduler:
echo    Start -^> Search "Task Scheduler"
echo.
echo 3. View logs:
echo    %%TEMP%%\femas_checkin.log
echo    %%TEMP%%\femas_checkout.log
echo.
echo 4. Manual test:
echo    checkin.bat  (Check-in)
echo    checkout.bat (Check-out)
echo.
echo 5. Uninstall:
echo    Run: uninstall.bat
echo.
pause
